version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    restart: unless-stopped
    networks:
      - app-network
    ports: 
      - "80:8181"    
    depends_on:
        db:
            condition: service_healthy
  # MySQL service
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped 
    # ports:
    #    - "3306:3306"  # not required but could be opened
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10    

# Redis Service      
  cache:
    image: redis:alpine
    container_name: redis-as-cache
    restart: unless-stopped
    # ports:
    #  -  "6379:6379"  # not required but could be opened.
    networks:
      - app-network



#Docker Networks
networks:
  app-network:
    driver: bridge